### ISSUE TITLE
NoScopes sound trigger not working

### ISSUE THREAD

**Issue by Stepepper** [Stepepper/CoolDoom#13]
I added NoScope death states to the IMP and ZOMBIEMEN but they don't seem to work, they also don't seem to add the Inventory item: noscopedYo to the inventory, so the sound doesn't play. Well that's probably because the death states don't work.

I think this is a fault with Brutal Doom's death system or something but idk.

**Comment by BoxcarRacer41** [comment]
no its because ur retarded u fucking shtudppid shit lemme try

**Comment by Stepepper** [comment]
yes

**Comment by BoxcarRacer41** [comment]
it was A_GiveToTarget not A_GiveInventory mmkay nerd
