### ISSUE TITLE
Parkour features accessible with all classes

### ISSUE THREAD

**Issue by BoxcarRacer41** [Stepepper/CoolDoom#4]
Parkour features (Double jump, wall jump etc.) should be exclusive to the Cool Doomer class, but for some reason are accessible by all of them. FIXI T FGAOGHT

**Comment by Stepepper** [comment]
i have cancer

**Comment by BoxcarRacer41** [comment]
eh its not a bug ITS A FEATURE MOM!

**Comment by BoxcarRacer41** [comment]
eh its not a bug ITS A FEATURE MOM!
